// Generates the config that loads the injection rewrite. The rules it
// follows live in wrapper-config.ts, shared with every other verb.
//
// The file sits with the verb, as probe-config.ts does. The plugin it
// names stays in src/, so the path is one directory up: a sibling path
// from here would look for the plugin inside src/verbs.
import { dirname, resolve } from "node:path";
import { modulePath } from "../sibling.ts";
import { writeGeneratedConfig, type Wrapper } from "../wrapper-config.ts";

const PLUGIN_MODULE = modulePath("../exec-plugin", import.meta.url);

export interface ExecWrapperInput {
  cwd: string;
  targetPath: string;
  targetName: string;
  targetLine: number;
  targetColumn: number;
  atLine: number;
  expression: string;
}

export function writeExecWrapperConfig(input: ExecWrapperInput): Wrapper {
  return writeGeneratedConfig({
    cwd: input.cwd,
    slug: "exec",
    projectFor: dirname(resolve(input.cwd, input.targetPath)),
    pluginModule: PLUGIN_MODULE,
    pluginExport: "depugExecPlugin",
    pluginOptions: [
      "{",
      `  root: ${JSON.stringify(input.cwd)},`,
      `  targetPath: ${JSON.stringify(input.targetPath)},`,
      `  targetName: ${JSON.stringify(input.targetName)},`,
      `  targetLine: ${JSON.stringify(input.targetLine)},`,
      `  targetColumn: ${JSON.stringify(input.targetColumn)},`,
      `  atLine: ${JSON.stringify(input.atLine)},`,
      `  expression: ${JSON.stringify(input.expression)},`,
      "}",
    ].join("\n"),
    comment: [
      "Generated by depug for one exec run. It adds depug's statement",
      "injection for one line of one function and changes nothing else.",
    ],
  });
}
