// Generates the config that loads the probe rewrite into a project's own
// test run.
//
// It is a near twin of the one wrapper-config.ts writes for the call
// index, and it stays a separate function rather than a parameter on that
// one: the two differ in which plugin they add and in nothing else today,
// and a shared function with a mode flag would make both harder to read
// than either is now. The rules they do share -- where the file goes, and
// why -- are documented there.
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { findProjectConfig, type Wrapper } from "../wrapper-config.ts";

const PLUGIN_MODULE = fileURLToPath(new URL("../probe-plugin.ts", import.meta.url));

export interface ProbeWrapperInput {
  cwd: string;
  targets: readonly string[];
}

export function writeProbeWrapperConfig(input: ProbeWrapperInput): Wrapper {
  const base = findProjectConfig(input.cwd);
  const holder = join(input.cwd, "node_modules", ".depug");
  mkdirSync(holder, { recursive: true });
  const dir = mkdtempSync(join(holder, "probe-"));
  const configPath = join(dir, "vitest.depug-probe.config.ts");

  const added = [
    "const added = defineConfig({",
    "  plugins: [",
    "    depugProbePlugin({",
    `      root: ${JSON.stringify(input.cwd)},`,
    `      targets: ${JSON.stringify(input.targets)},`,
    "    }),",
    "  ],",
    "});",
  ];

  const lines = [
    "// Generated by depug for one probe run. It adds the probe plugin to",
    "// the project's own config and changes nothing else.",
    'import { defineConfig, mergeConfig } from "vitest/config";',
    `import { depugProbePlugin } from ${JSON.stringify(PLUGIN_MODULE)};`,
    ...(base
      ? [
          `import baseConfig from ${JSON.stringify(base)};`,
          "",
          ...added,
          "",
          "export default mergeConfig(baseConfig, added);",
        ]
      : ["", ...added, "", "export default added;"]),
  ];

  writeFileSync(configPath, `${lines.join("\n")}\n`);
  return {
    configPath,
    dir,
    baseConfig: base ?? null,
    cleanup: () => rmSync(dir, { recursive: true, force: true }),
  };
}
