// Generates the config that loads the probe rewrite into a project's own
// test run. The rules it follows -- where the file goes, and why -- live
// in wrapper-config.ts, which every verb's generated config shares.
import { fileURLToPath } from "node:url";
import { writeGeneratedConfig, type Wrapper } from "../wrapper-config.ts";

const PLUGIN_MODULE = fileURLToPath(new URL("../probe-plugin.ts", import.meta.url));

export interface ProbeWrapperInput {
  cwd: string;
  targets: readonly string[];
}

export function writeProbeWrapperConfig(input: ProbeWrapperInput): Wrapper {
  return writeGeneratedConfig({
    cwd: input.cwd,
    slug: "probe",
    pluginModule: PLUGIN_MODULE,
    pluginExport: "depugProbePlugin",
    pluginOptions: `{ root: ${JSON.stringify(input.cwd)}, targets: ${JSON.stringify(input.targets)} }`,
    comment: [
      "Generated by depug for one probe run. It adds the probe plugin to",
      "the project's own config and changes nothing else.",
    ],
  });
}
