// Generates the config that loads the per-statement rewrite into a
// project's own test run. The rules it follows -- where the file goes, why
// it goes there, and how a project with no config of its own is handled --
// live in wrapper-config.ts, which every verb's generated config shares.
import { fileURLToPath } from "node:url";
import { writeGeneratedConfig, type Wrapper } from "./wrapper-config.ts";

const PLUGIN_MODULE = fileURLToPath(new URL("./flt-plugin.ts", import.meta.url));

export interface FltWrapperTarget {
  path: string;
  name: string;
  line: number;
  column: number;
}

export interface FltWrapperInput {
  cwd: string;
  baseConfig?: string;
  target: FltWrapperTarget;
}

export type FltWrapper = Wrapper;

export function writeFltWrapperConfig(input: FltWrapperInput): FltWrapper {
  return writeGeneratedConfig({
    cwd: input.cwd,
    baseConfig: input.baseConfig,
    slug: "flt",
    pluginModule: PLUGIN_MODULE,
    pluginExport: "depugFltPlugin",
    pluginOptions: [
      "{",
      `  root: ${JSON.stringify(input.cwd)},`,
      `  targetPath: ${JSON.stringify(input.target.path)},`,
      `  targetName: ${JSON.stringify(input.target.name)},`,
      `  targetLine: ${JSON.stringify(input.target.line)},`,
      `  targetColumn: ${JSON.stringify(input.target.column)},`,
      "}",
    ].join("\n"),
    comment: [
      "Generated by depug for one flt re-execution. It adds depug's",
      "per-statement instrumentation for one function to the project's own",
      "config and changes nothing else.",
    ],
  });
}
