// Loads the flt plugin into a project's test run without editing that
// project's own vitest config, the way src/wrapper-config.ts does for the
// always-on layer. See that module's own header for why the generated
// file lives under the project's own node_modules/.depug rather than a
// system temp directory, and why each invocation gets a fresh one.
//
// This reuses wrapper-config.ts's `findProjectConfig` and
// `applyConfigArgument`: both only read a project's own config or rewrite
// a command line, neither is specific to the always-on plugin, and
// duplicating them would let the two copies drift silently.
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { findProjectConfig } from "./wrapper-config.ts";

const PLUGIN_MODULE = fileURLToPath(new URL("./flt-plugin.ts", import.meta.url));

export interface FltWrapperTarget {
  path: string;
  name: string;
  line: number;
  column: number;
}

export interface FltWrapperInput {
  cwd: string;
  baseConfig?: string;
  target: FltWrapperTarget;
}

export interface FltWrapper {
  configPath: string;
  dir: string;
  baseConfig: string | null;
  cleanup(): void;
}

export function writeFltWrapperConfig(input: FltWrapperInput): FltWrapper {
  const base = input.baseConfig
    ? isAbsolute(input.baseConfig)
      ? input.baseConfig
      : resolve(input.cwd, input.baseConfig)
    : findProjectConfig(input.cwd);

  const holder = join(input.cwd, "node_modules", ".depug");
  mkdirSync(holder, { recursive: true });
  const dir = mkdtempSync(join(holder, "flt-run-"));
  const configPath = join(dir, "vitest.depug-flt.config.ts");

  const header = [
    "// Generated by depug for one flt re-execution. It adds depug's",
    "// per-statement instrumentation for one function to the project's own",
    "// config and changes nothing else.",
    'import { defineConfig, mergeConfig } from "vitest/config";',
    `import { depugFltPlugin } from ${JSON.stringify(PLUGIN_MODULE)};`,
  ];

  const added = [
    "const added = defineConfig({",
    "  plugins: [",
    "    depugFltPlugin({",
    `      root: ${JSON.stringify(input.cwd)},`,
    `      targetPath: ${JSON.stringify(input.target.path)},`,
    `      targetName: ${JSON.stringify(input.target.name)},`,
    `      targetLine: ${JSON.stringify(input.target.line)},`,
    `      targetColumn: ${JSON.stringify(input.target.column)},`,
    "    }),",
    "  ],",
    "});",
  ];

  const body = base
    ? [
        `import baseConfig from ${JSON.stringify(base)};`,
        "",
        ...added,
        "",
        "export default mergeConfig(baseConfig, added);",
      ]
    : ["", ...added, "", "export default added;"];

  writeFileSync(configPath, `${[...header, ...body].join("\n")}\n`);
  return {
    configPath,
    dir,
    baseConfig: base ?? null,
    cleanup: () => rmSync(dir, { recursive: true, force: true }),
  };
}
