// Loads depug into a project's test run without editing that project's
// own vitest config.
//
// The generated file imports the project's config and merges the plugin
// into it, so every setting the project already had stays in force. The
// alternative, telling a user to add a plugin line, puts depug into a file
// that belongs to their repository for as long as they want to use a verb
// once.
//
// The file goes under the project's own `node_modules/.depug`, not a
// system temp directory. A generated config imports `vitest/config` by
// name, and Node resolves a bare name by walking up from the importing
// file: from a temp directory that walk finds no `node_modules` at all and
// the config fails to load. Writing it inside the project puts the
// project's own dependencies back on that path, while keeping the file out
// of the source tree. Each wrapper gets a unique name so two verbs running
// at once do not share one.
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PLUGIN_MODULE = fileURLToPath(new URL("./plugin.ts", import.meta.url));

// vitest resolves these in order when no `--config` is given. depug looks
// for the same ones so the wrapper starts from the config the project's
// own run would have used.
const CONFIG_NAMES = [
  "vitest.config.ts",
  "vitest.config.mts",
  "vitest.config.js",
  "vitest.config.mjs",
  "vite.config.ts",
  "vite.config.mts",
  "vite.config.js",
  "vite.config.mjs",
];

export function findProjectConfig(cwd: string): string | undefined {
  for (const name of CONFIG_NAMES) {
    const candidate = join(cwd, name);
    if (existsSync(candidate)) return candidate;
  }
  return undefined;
}

export interface WrapperInput {
  cwd: string;
  /** The project's own config; found from `cwd` when not given. */
  baseConfig?: string;
  /** Absolute paths of the files to instrument, or a predicate source. */
  includePathPrefix: string;
}

export interface Wrapper {
  configPath: string;
  dir: string;
  /** The project config this wrapper builds on, or null where none was found. */
  baseConfig: string | null;
  /** Removes the generated file. Safe to call more than once. */
  cleanup(): void;
}

/**
 * Writes the wrapper and returns where it went.
 *
 * With no project config to build on, the wrapper defines one from
 * nothing. vitest runs happily without a config file, and a project in
 * that position should not be told to write one before it can use a verb.
 */
export function writeWrapperConfig(input: WrapperInput): Wrapper {
  const base = input.baseConfig
    ? isAbsolute(input.baseConfig)
      ? input.baseConfig
      : resolve(input.cwd, input.baseConfig)
    : findProjectConfig(input.cwd);

  const holder = join(input.cwd, "node_modules", ".depug");
  mkdirSync(holder, { recursive: true });
  const dir = mkdtempSync(join(holder, "run-"));
  const configPath = join(dir, "vitest.depug.config.ts");

  const includeLiteral = JSON.stringify(input.includePathPrefix);
  const header = [
    "// Generated by depug for one re-execution. It adds the depug plugin",
    "// to the project's own config and changes nothing else.",
    'import { defineConfig, mergeConfig } from "vitest/config";',
    `import { depugPlugin } from ${JSON.stringify(PLUGIN_MODULE)};`,
  ];

  const added = [
    "const added = defineConfig({",
    "  plugins: [",
    "    depugPlugin({",
    `      root: ${JSON.stringify(input.cwd)},`,
    "      include: (id) =>",
    `        id.startsWith(${includeLiteral}) &&`,
    '        !id.includes("/node_modules/") &&',
    "        /\\.tsx?$/.test(id) &&",
    "        !/\\.(test|spec)\\.tsx?$/.test(id),",
    "    }),",
    "  ],",
    "});",
  ];

  const body = base
    ? [
        `import baseConfig from ${JSON.stringify(base)};`,
        "",
        ...added,
        "",
        "export default mergeConfig(baseConfig, added);",
      ]
    : ["", ...added, "", "export default added;"];

  writeFileSync(configPath, `${[...header, ...body].join("\n")}\n`);
  return {
    configPath,
    dir,
    baseConfig: base ?? null,
    cleanup: () => rmSync(dir, { recursive: true, force: true }),
  };
}

/**
 * Rewrites a child command so it runs under the wrapper.
 *
 * A `--config` the caller already passed names the config depug should
 * build on, so it is taken as the base and removed; leaving both in place
 * would let vitest pick one and silently drop the plugin.
 */
export function applyConfigArgument(args: readonly string[], configPath: string): {
  args: string[];
  replaced: string | null;
} {
  const out: string[] = [];
  let replaced: string | null = null;
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--config" || arg === "-c") {
      replaced = args[i + 1] ?? null;
      i += 1;
      continue;
    }
    if (arg.startsWith("--config=")) {
      replaced = arg.slice("--config=".length);
      continue;
    }
    out.push(arg);
  }
  out.push("--config", configPath);
  return { args: out, replaced };
}
