// Loads depug into a project's test run without editing that project's
// own vitest config.
//
// The generated file imports the project's config and merges the plugin
// into it, so every setting the project already had stays in force. The
// alternative, telling a user to add a plugin line, puts depug into a file
// that belongs to their repository for as long as they want to use a verb
// once.
//
// The file goes under the project's own `node_modules/.depug`, not a
// system temp directory. A generated config imports `vitest/config` by
// name, and Node resolves a bare name by walking up from the importing
// file: from a temp directory that walk finds no `node_modules` at all and
// the config fails to load. Writing it inside the project puts the
// project's own dependencies back on that path, while keeping the file out
// of the source tree. Each wrapper gets a unique name so two verbs running
// at once do not share one.
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PLUGIN_MODULE = fileURLToPath(new URL("./plugin.ts", import.meta.url));

// vitest resolves these in order when no `--config` is given. depug looks
// for the same ones so the wrapper starts from the config the project's
// own run would have used.
const CONFIG_NAMES = [
  "vitest.config.ts",
  "vitest.config.mts",
  "vitest.config.js",
  "vitest.config.mjs",
  "vite.config.ts",
  "vite.config.mts",
  "vite.config.js",
  "vite.config.mjs",
];

export function findProjectConfig(cwd: string): string | undefined {
  for (const name of CONFIG_NAMES) {
    const candidate = join(cwd, name);
    if (existsSync(candidate)) return candidate;
  }
  return undefined;
}

/**
 * True where a project's config splits the run into vitest projects.
 *
 * This matters because vitest does not apply a root config's `plugins` to
 * a project's own config, so a wrapper built by merging into the root
 * reaches none of the code under test. depug records nothing and, without
 * this check, reports it as an include path that matched no files, which
 * sends a reader to fix the one thing that was not wrong.
 *
 * The check reads the config's text rather than importing it: importing an
 * arbitrary project config runs it, and this question does not need the
 * answer badly enough to do that.
 */
export function declaresProjects(configPath: string | undefined): boolean {
  if (!configPath || !existsSync(configPath)) return false;
  const text = readFileSync(configPath, "utf8");
  return /(^|[^\w.])projects\s*:/.test(text) || /\bworkspace\s*:/.test(text);
}

export interface WrapperInput {
  cwd: string;
  /** The project's own config; found from `cwd` when not given. */
  baseConfig?: string;
  /** Absolute paths of the files to instrument, or a predicate source. */
  includePathPrefix: string;
}

export interface Wrapper {
  configPath: string;
  dir: string;
  /** The project config this wrapper builds on, or null where none was found. */
  baseConfig: string | null;
  /** Removes the generated file. Safe to call more than once. */
  cleanup(): void;
}

/**
 * Writes the wrapper and returns where it went.
 *
 * With no project config to build on, the wrapper defines one from
 * nothing. vitest runs happily without a config file, and a project in
 * that position should not be told to write one before it can use a verb.
 */
export function writeWrapperConfig(input: WrapperInput): Wrapper {
  const includeLiteral = JSON.stringify(input.includePathPrefix);
  return writeGeneratedConfig({
    cwd: input.cwd,
    baseConfig: input.baseConfig,
    slug: "run",
    pluginModule: PLUGIN_MODULE,
    pluginExport: "depugPlugin",
    projectFor: input.includePathPrefix,
    pluginOptions: [
      "{",
      `  root: ${JSON.stringify(input.cwd)},`,
      "  include: (id) =>",
      `    id.startsWith(${includeLiteral}) &&`,
      '    !id.includes("/node_modules/") &&',
      "    /\\.tsx?$/.test(id) &&",
      "    !/\\.(test|spec)\\.tsx?$/.test(id),",
      "}",
    ].join("\n"),
    comment: [
      "Generated by depug for one re-execution. It adds the depug plugin",
      "to the project's own config and changes nothing else.",
    ],
  });
}

/**
 * The nearest config at or above `startPath`, stopping at `cwd`.
 *
 * In a repository split into vitest projects, the config that governs the
 * code under test is the one in that package, not the one at the root.
 */
export function findEnclosingProjectConfig(
  startPath: string,
  cwd: string,
): { configPath: string; root: string } | undefined {
  let dir = startPath;
  for (;;) {
    const found = findProjectConfig(dir);
    if (found && resolve(dir) !== resolve(cwd)) return { configPath: found, root: dir };
    const parent = dirname(dir);
    if (parent === dir || resolve(dir) === resolve(cwd)) return undefined;
    dir = parent;
  }
}

export interface GeneratedConfigInput {
  cwd: string;
  /** The project's own config; found from `cwd` when not given. */
  baseConfig?: string;
  /** Distinguishes one verb's generated directory from another's. */
  slug: string;
  /** Absolute path of the module exporting the plugin. */
  pluginModule: string;
  pluginExport: string;
  /**
   * The plugin's argument, already rendered as JavaScript source. A caller
   * passes source rather than a value because some options are functions,
   * which JSON cannot carry into a generated file.
   */
  pluginOptions: string;
  /** Header comment lines, without the leading slashes. */
  comment: string[];
  /**
   * A path inside the code to instrument. Used only where the project's
   * config splits the run into vitest projects, to find the project that
   * owns that code.
   */
  projectFor?: string;
}

/**
 * Writes one generated config that adds one plugin to the project's own.
 *
 * Every verb needs this and they differ only in which plugin they add and
 * what they pass it. Writing it once means the rules that matter -- where
 * the file goes, how a missing project config is handled, and that the
 * project's own settings survive -- hold for every verb rather than for
 * whichever copies were remembered.
 */
export function writeGeneratedConfig(input: GeneratedConfigInput): Wrapper {
  const base = input.baseConfig
    ? isAbsolute(input.baseConfig)
      ? input.baseConfig
      : resolve(input.cwd, input.baseConfig)
    : findProjectConfig(input.cwd);

  const holder = join(input.cwd, "node_modules", ".depug");
  mkdirSync(holder, { recursive: true });
  const dir = mkdtempSync(join(holder, `${input.slug}-`));
  const configPath = join(dir, `vitest.depug-${input.slug}.config.ts`);

  // vitest does not apply a root config's `plugins` to a project's own
  // config, so merging the plugin into the root reaches none of the code
  // under test. Naming the project inline, with its own config extended
  // and its own directory as the root, puts the plugin where the code is
  // and leaves every relative path in that config resolving as it did.
  const project =
    input.projectFor && declaresProjects(base)
      ? findEnclosingProjectConfig(input.projectFor, input.cwd)
      : undefined;

  const added = project
    ? [
        "const added = defineConfig({",
        "  test: {",
        "    projects: [",
        "      {",
        `        extends: ${JSON.stringify(project.configPath)},`,
        `        root: ${JSON.stringify(project.root)},`,
        `        plugins: [${input.pluginExport}(${input.pluginOptions})],`,
        "      },",
        "    ],",
        "  },",
        "});",
      ]
    : [
        "const added = defineConfig({",
        `  plugins: [${input.pluginExport}(${input.pluginOptions})],`,
        "});",
      ];

  const lines = [
    ...input.comment.map((line) => `// ${line}`),
    'import { defineConfig, mergeConfig } from "vitest/config";',
    `import { ${input.pluginExport} } from ${JSON.stringify(input.pluginModule)};`,
    ...(base
      ? [
          `import baseConfig from ${JSON.stringify(base)};`,
          "",
          ...added,
          "",
          "export default mergeConfig(baseConfig, added);",
        ]
      : ["", ...added, "", "export default added;"]),
  ];

  writeFileSync(configPath, `${lines.join("\n")}\n`);
  return {
    configPath,
    dir,
    baseConfig: base ?? null,
    cleanup: () => rmSync(dir, { recursive: true, force: true }),
  };
}

/**
 * Rewrites a child command so it runs under the wrapper.
 *
 * A `--config` the caller already passed names the config depug should
 * build on, so it is taken as the base and removed; leaving both in place
 * would let vitest pick one and silently drop the plugin.
 */
export function applyConfigArgument(args: readonly string[], configPath: string): {
  args: string[];
  replaced: string | null;
} {
  const out: string[] = [];
  let replaced: string | null = null;
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--config" || arg === "-c") {
      replaced = args[i + 1] ?? null;
      i += 1;
      continue;
    }
    if (arg.startsWith("--config=")) {
      replaced = arg.slice("--config=".length);
      continue;
    }
    out.push(arg);
  }
  out.push("--config", configPath);
  return { args: out, replaced };
}
